language: csharp
mono: none
sudo: required
dist: xenial
dotnet: 2.2

services:
  - docker

script:
  - dotnet restore
  - dotnet build
  - dotnet test
  - dotnet publish -c Release -o ./publish
  - docker build -t goodboyymh/weshop:latest .

global:
  - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
  - DOTNET_CLI_TELEMETRY_OPTOUT=1

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD;
    docker push goodboyymh/weshop:latest;
    fi

os:
  - linux

branches:
  only:
    - master
