language: csharp
mono: none
sudo: required
dist: xenial

services:
  - docker

script:
  - docker build -t ${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_VERSION} .

global:
  - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
  - DOTNET_CLI_TELEMETRY_OPTOUT=1

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD;
    docker push ${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_VERSION};
    fi

os:
  - linux

branches:
  only:
    - master
