language: csharp
mono: none
sudo: required
dist: trusty

before_install:
  - wget -q https://packages.microsoft.com/config/ubuntu/16.04/packages-microsoft-prod.deb
  - sudo dpkg -i packages-microsoft-prod.deb
  - sudo apt-get install apt-transport-https
  - sudo apt-get update
  - sudo add-apt-repository universe
  - sudo apt-get install dotnet-sdk-2.2
services:
  - docker

script:
  - dotnet restore
  - dotnet build
  - dotnet test
  - dotnet publish -c Release -o ./publish
  - docker build -t goodboyymh/weshop:latest .

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD;
    docker push goodboyymh/weshop:latest;
    fi

os:
  - linux

branches:
  only:
    - master
